apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-caddyfile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mu2edaq-pager.labels" . | nindent 4 }}
data:
  Caddyfile: |
    :8080 {
        encode gzip
        {{- if .Values.backend.tunnel.enabled }}
        reverse_proxy {{ printf "%s://127.0.0.1:%v" .Values.backend.tunnel.scheme .Values.backend.tunnel.localPort }} {
        {{- if eq .Values.backend.tunnel.scheme "https" }}
            transport http {
                tls_insecure_skip_verify
            }
        {{- end }}
        {{- else }}
        reverse_proxy {{ required "backend.url is required -- set it in my-values.yaml" .Values.backend.url }} {
        {{- if hasPrefix "https://" .Values.backend.url }}
            transport http {
                tls_insecure_skip_verify
            }
        {{- end }}
        {{- end }}
        }
    }
